title: Thiago Marinho
author: Thiago Marinho
url: thiagomarinho.net

twitter_username: thiagomarinho
github_username: thiagomarinho
linkedin_username: thiagoomarinho

google_analytics: UA-21612517-1

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-multiple-languages-plugin

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
languages: ["pt-br", "en"]
exclude_from_localizations: ["javascript", "images", "css"]