title: Thiago Marinho

site:
  author:
    name: Thiago Marinho

header_pages:
  - about.md
  - projects.md

google_analytics: UA-21612517-1

plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:
  skin: dark