title: Thiago Marinho
author: Thiago Marinho

github_username:  thiagomarinho
linkedin_username: thiagoomarinho

description: :)

header_pages:
  - about.md
  - projects.md

google_analytics: UA-21612517-1

plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:
  skin: dark