title: Thiago Marinho
theme: minima

header_pages:
  - about.md

minima:
  social_links:
    twitter: thiagomarinho
    github: thiagomarinho
    telegram: thiagomarinho
    facebook: thiagoomarinho
    linkedin: thiagoomarinho
